---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Install Base Packages
    package:
      name: 
        - git
        - neovim
        - btop

  - name: Copy Wallpaper
    copy:
      src: files/wallpapers/wallpaper.jpg
      dest: ~/Wallpapers/ansible-wallpaper.jpg
      owner: root
      group: root
